<!-- MHonArc v2.6.16 -->
<!--X-Subject: Failure of a few unit tests in Python 3.2. -->
<!--X-From-R13: "Sqjneq q'Ohiretar" <rqjneqNaze&#45;erynk.pbz> -->
<!--X-Date: Fri, 28 Feb 2014 18:51:02 +0100 -->
<!--X-Message-Id: CAED9pY_1=3uYv96_K5Kqk0no2nAKEOr9bH2fanMXsr1cB7YviQ@mail.gmail.com -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Failure of a few unit tests in Python 3.2. -- February 28, 2014 - 18:51</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Failure of a few unit tests in Python 3.2.</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00191" class="tabs">Index by Date</a> | <a href="threads.html#00191" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00190.html">Date Prev</a>] [Date Next] [<a href="msg00190.html">Thread Prev</a>] [Thread Next]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: &quot;relax-devel@xxxxxxx&quot; &lt;relax-devel@xxxxxxx&gt;</li>
<li class="menuitem">
<em>Date</em>: Fri, 28 Feb 2014 18:50:28 +0100</li>
<li class="menuitem">
<em>Dkim-signature</em>: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=20120113;	h=mime-version:sender:date:message-id:subject:from:to:content-type	:content-transfer-encoding;	bh=b9xqwpMU/bDGOIcGTGjE9oZyqx9x9HXORr9TlYUVtXo=;	b=SMKmymXqPScELvcYxGq8vdvh+s51lEpU5JUw7wpeX6d3Xm4ONjp7fDtrqIkDK7dpt6	uNuh9Ttnp4piwhbj375zPXz1AAM/tMeyOjtJNvd0lTK7gWc+di3EZHxLuUjsGSkFuVl4	NqAMm48+2sA96ioVocgW+AH7jQiS0bBjHdf8h9v/eSctUU5t0m0A+/9lTwe9Jkvz3f3F	6HUy+8WfZPctpvvqUnpINQZ1KAPRTpyz2cxTcfzAZKUNF4eSUM43bmckBbKzZaM2OXoG	chWQ6bJLipX0UvGoFYz6UPVyJ3VlseGeE/wt3lB5bKdinQYqX4TdjHPU5dIHgjqrBBiA	dCew==</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00191.html">CAED9pY_1=3uYv96_K5Kqk0no2nAKEOr9bH2fanMXsr1cB7YviQ@mail.gmail.com</a>&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Edward d'Auvergne</strong> on February 28, 2014 - 18:51:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">Hi Troels,

I have been running the
devel_scripts/python_multiversion_test_suite.py script on a virtual
machine with a 32-bit Linux test system (Mageia 4) and have noticed
that some of your unit tests fail.  For Python 2.5, 2.6, 2.7, and 3.1
the tests pass, but on Python 3.2 and 3.3 they fail.  This is for
relax 3.1.6 which I have almost finished releasing.  The error
messages from the test suite are below.  I'm not sure exactly what the
problem is, but you might need to consider changing the string
formatting &quot;%s_%s&quot; to use float formatting &quot;.3f&quot; (here 3 mean 3
decimal places, so you'd need to change it to suit).

Cheers,

Edward


P. S.  The messages I see are:


==============
= Unit tests =
==============

.....................................................................EE...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================
ERROR: test_count_relax_times_r1rho
(test_suite.unit_tests._specific_analyses._relax_disp.test_disp_data.Test_disp_data)
Unit test of the count_relax_times() function.
----------------------------------------------------------------------
Opening the file
'/data/relax/relax-trunk/test_suite/shared_data/dispersion/bug_21344_trunc.bz2'
for reading.
Checking the number of time counts.
13_500_46_40 R1rho 799777399.1 124.24703146206046 1341.11 5
Traceback (most recent call last):
  File 
&quot;/data/relax/relax-trunk/test_suite/unit_tests/_specific_analyses/_relax_disp/test_disp_data.py&quot;,
line 196, in test_count_relax_times_r1rho
    self.assertEqual(count, time_comp['%s_%s'%(offset, point)])
KeyError: '124.24703146206046_1341.11'

======================================================================
ERROR: test_find_intensity_keys_r1rho
(test_suite.unit_tests._specific_analyses._relax_disp.test_disp_data.Test_disp_data)
Unit test of the find_intensity_keys() function.
----------------------------------------------------------------------
Opening the file
'/data/relax/relax-trunk/test_suite/shared_data/dispersion/bug_21344_trunc.bz2'
for reading.
Checking the id return experiment.
Traceback (most recent call last):
  File 
&quot;/data/relax/relax-trunk/test_suite/unit_tests/_specific_analyses/_relax_disp/test_disp_data.py&quot;,
line 293, in test_find_intensity_keys_r1rho
    print(exp_type, frq, offset, point, time, data[&quot;%s_%s_%s&quot;%(offset,
point, time)][5], id, ids)
KeyError: '124.24703146206046_1341.11_0.0'

----------------------------------------------------------------------
Ran 1286 tests in 10.743s

FAILED (errors=2)


</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Fri Feb 28 19:00:09 2014</div>  
</body>
</html>
