<!-- MHonArc v2.6.10 -->
<!--X-Subject: Re: [bug #5746] TypeError on dx.map() &#45; Bad call to	specific.model_free.model_statistics() ? -->
<!--X-From-R13: "Sqjneq q'Ohiretar" <rqjneq.qnhiretarNtznvy.pbz> -->
<!--X-Date: Tue, 11 Apr 2006 09:06:01 +0200 -->
<!--X-Message-Id: 7f080ed10604110003i51ff96c4ja78da8d089b4a040@mail.gmail.com -->
<!--X-Content-Type: text/plain -->
<!--X-Reference: 20060410&#45;104402.sv4125.58048@gna.org -->
<!--X-Reference: 7f080ed10604102345r1bfb002fle059d7043025ed9e@mail.gmail.com -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Re: [bug #5746] TypeError on dx.map() - Bad call to	specific.model_free.model_statistics() ? -- April 11, 2006 - 09:06</title>
<link rel="stylesheet" type="text/css" href="/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="https://gna.org/images/gna.theme/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Re: [bug #5746] TypeError on dx.map() - Bad call to	specific.model_free.model_statistics() ?</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00019" class="tabs">Index by Date</a> | <a href="threads.html#00019" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00018.html">Date Prev</a>] [<a href="msg00020.html">Date Next</a>] [<a href="msg00018.html">Thread Prev</a>] [<a href="msg00020.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: relax-devel@xxxxxxx</li>
<li class="menuitem">
<em>Date</em>: Tue, 11 Apr 2006 17:03:22 +1000</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00019.html">7f080ed10604110003i51ff96c4ja78da8d089b4a040@mail.gmail.com</a>&gt;</li>
<li class="menuitem">
<em>References</em>: &lt;20060410-104402.sv4125.58048@gna.org&gt;	&lt;<a href="msg00018.html">7f080ed10604102345r1bfb002fle059d7043025ed9e@mail.gmail.com</a>&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Edward d'Auvergne</strong> on April 11, 2006 - 09:06:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">I've solved the problem to bug #5746 located at
<a  href="https://gna.org/bugs/?func=detailitem&amp;item_id=5746">https://gna.org/bugs/?func=detailitem&amp;item_id=5746</a>.  The issue was
simply an incorrect test in the 'self.model_statistics()' function of
the model-free specific code.  The diff of the fix is:

Index: specific_fns/model_free.py
===================================================================
--- specific_fns/model_free.py  (revision 2461)
+++ specific_fns/model_free.py  (working copy)
@@ -2515,7 +2515,7 @@

         # Sequence specific data.
         # Statistics for a single residue.
-        if not global_stats and not combine:
+        if not global_stats or not combine:
             # Skip unselected residues.
             if not self.relax.data.res[self.run][instance].select:
                 return None, None, None


Edward


On 4/11/06, Edward d'Auvergne &lt;edward.dauvergne@xxxxxxxxx&gt; wrote:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">I have a feeling this is a failure of the model-free
'self.calculate()' function.  The chi2 value should be a floating
point number, not None.  I have to admit that the 'instance',
'min_instances', and 'num_instances' flags are a bit confusing.

Edward


On 4/10/06, Chris MacRaild &lt;NO-REPLY.INVALID-ADDRESS@xxxxxxx&gt; wrote:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">

URL:
  &lt;<a  href="http://gna.org/bugs/?func=detailitem&amp;item_id=5746">http://gna.org/bugs/?func=detailitem&amp;item_id=5746</a>&gt;

                 Summary: TypeError on dx.map() - Bad call to
specific.model_free.model_statistics() ?
                 Project: relax
            Submitted by: macraild
            Submitted on: Monday 04/10/2006 at 10:44
                Category: None
                Priority: 5 - Normal
                Severity: 4 - Important
                  Status: None
                 Privacy: Public
             Assigned to: None
         Originator Name:
        Originator Email:
             Open/Closed: Open
                 Release: Repository: 1.2 line
        Operating System: None

    _______________________________________________________

Details:

With the attached data and script, the dx.map() call raises a TypeError:

Creating the map.
Opening the file 'dx/map' for writing.
Progress:    0.000%
Traceback (most recent call last):
  File &quot;1.2/relax&quot;, line 415, in ?
    Relax()
  File &quot;1.2/relax&quot;, line 147, in __init__
    self.interpreter.run()
  File &quot;/home/chris/relax_devel/1.2_5698_fix/prompt/interpreter.py&quot;, line
213, in run
  File &quot;/home/chris/relax_devel/1.2_5698_fix/prompt/interpreter.py&quot;, line
385, in run_script
  File &quot;/home/chris/relax_devel/1.2_5698_fix/prompt/interpreter.py&quot;, line
340, in interact_script
  File &quot;map.py&quot;, line 62, in ?
    dx.map(name, params=params, res_num=3, inc=inc, lower=lower, 
upper=upper,
point=point)
  File &quot;/home/chris/relax_devel/1.2_5698_fix/prompt/dx.py&quot;, line 279, in 
map
  File &quot;/home/chris/relax_devel/1.2_5698_fix/dx/opendx.py&quot;, line 59, in 
map
  File &quot;/home/chris/relax_devel/1.2_5698_fix/dx/base_map.py&quot;, line 350, in
map_space
  File &quot;/home/chris/relax_devel/1.2_5698_fix/dx/base_map.py&quot;, line 81, in
create_map
  File &quot;/home/chris/relax_devel/1.2/dx/isosurface_3D.py&quot;, line 107, in
map_text
    k, n, chi2 = self.model_stats(run=self.run, instance=self.index,
min_instances=1)
  File &quot;/home/chris/relax_devel/1.2/specific_fns/model_free.py&quot;, line 
2555,
in model_statistics
    chi2 = chi2 + self.relax.data.res[self.run][i].chi2
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'


I've tried to trace this one, and I think the problem lies in the call to
specific.model_free.model_statistics(). Removing the min_instances keyword
arg seems to fix in this specific case, but I don't understand the 
intended
purpose of this argument in defining the behaviour of model_statistics().
Perhaps the more general fix lies elsewhere?





    _______________________________________________________

File Attachments:


-------------------------------------------------------
Date: Monday 04/10/2006 at 10:44  Name: dx.map_script_data.tar.bz2  Size:
8.02KB   By: macraild
Script and data which raise bug
&lt;<a  href="http://gna.org/bugs/download.php?file_id=793">http://gna.org/bugs/download.php?file_id=793</a>&gt;

    _______________________________________________________

Reply to this item at:

  &lt;<a  href="http://gna.org/bugs/?func=detailitem&amp;item_id=5746">http://gna.org/bugs/?func=detailitem&amp;item_id=5746</a>&gt;

_______________________________________________
  Message sent via/by Gna!
  <a  href="http://gna.org/">http://gna.org/</a>


</pre></blockquote><pre style="margin: 0em;">

</pre></blockquote><pre style="margin: 0em;">


</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00020" href="msg00020.html">Re: [bug #5746] TypeError on dx.map() - Bad call to	specific.model_free.model_statistics() ?</a></strong>
<ul><li><em>From:</em> Chris MacRaild</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<ul><li><strong>References</strong>:
<ul>
<li><strong><a name="00018" href="msg00018.html">Re: [bug #5746] TypeError on dx.map() - Bad call to	specific.model_free.model_statistics() ?</a></strong>
<ul><li><em>From:</em> Edward d'Auvergne</li></ul></li>
</ul></li></ul>
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer">You are on the <a href="http://gna.org">Gna!</a> mail server.</div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Tue Apr 11 13:40:30 2006</div>  
</body>
</html>
