<!-- MHonArc v2.6.16 -->
<!--X-Subject: Problem during "final" run of d'Auvergne Protocol -->
<!--X-From-R13: Vhtu DI Rnaangg <u.qnaanggNfurssvryq.np.hx> -->
<!--X-Date: Fri, 02 Mar 2012 12:34:39 +0100 -->
<!--X-Message-Id: CAJFDPzFu&#45;h1_=GKys3N7BOJbX&#45;QBbiAcF42v8W55EHb+NWMJNg@mail.gmail.com -->
<!--X-Content-Type: text/plain -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Problem during &quot;final&quot; run of d'Auvergne Protocol -- March 02, 2012 - 12:34</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Problem during &quot;final&quot; run of d'Auvergne Protocol</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00003" class="tabs">Index by Date</a> | <a href="threads.html#00003" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[Date Prev] [<a href="msg00000.html">Date Next</a>] [Thread Prev] [<a href="msg00005.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: &quot;relax-users@xxxxxxx&quot; &lt;relax-users@xxxxxxx&gt;</li>
<li class="menuitem">
<em>Date</em>: Fri, 2 Mar 2012 11:33:28 +0000</li>
<li class="menuitem">
<em>Authentication-results</em>: mr.google.com; spf=pass (google.com: domain of	h.dannatt@xxxxxxxxxxxxxxx designates 10.60.6.164 as permitted	sender) smtp.mail=h.dannatt@xxxxxxxxxxxxxxx</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00003.html">CAJFDPzFu-h1_=GKys3N7BOJbX-QBbiAcF42v8W55EHb+NWMJNg@mail.gmail.com</a>&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Hugh RW Dannatt</strong> on March 02, 2012 - 12:34:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">Dear All,

Having completed the fitting of 1 dataset without any problems, I am
now moving onto another. Everything has worked fine until I change the
DIFF_MODEL to &quot;final&quot; and try to run the program again to get error
estimates on my fitted parameters.

The program successfully re-opens all the results file and selects the
diffusion model. Then all 500 simulations are done without issue, but
as soon as the program has finished this, it stops outputting anything
to the screen for a long time (&gt;12 hrs). During this time, the CPU and
Memory use is very high and the computer runs slowly. Eventually I get
a &quot;Memory Error&quot; and a whole load of messages outputted to the screen,
which I have pasted below. I should emphasize that all the stages of
running this program with different diffusion models have run fine,
and the computer I'm using is a relatively fast machine (dual core
Pentium 4, 2 GB RAM).

Has anyone had a similar problem? This dataset is larger than the
previous one which fit without issue (current one has 6 measurements
per 176 residues), but I can't imagine this being the cause of this
problem.

Thanks

Hugh

----

Simulation 485
Simulation 486
Simulation 487
Simulation 488
Simulation 489
Simulation 490
Simulation 491
Simulation 492
Simulation 493
Simulation 494
Simulation 495
Simulation 496
Simulation 497
Simulation 498
Simulation 499
Simulation 500


Traceback (most recent call last):
  File &quot;/progs/relax-1.3.13/multi/uni_processor.py&quot;, line 136, in run
    self.callback.init_master(self)
  File &quot;/progs/relax-1.3.13/multi/processor.py&quot;, line 263, in
default_init_master
    self.master.run()
  File &quot;/progs/relax-1.3.13/relax.py&quot;, line 171, in run
    self.interpreter.run(self.script_file)
  File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 300, in run
    return run_script(intro=self.__intro_string, local=locals(),
script_file=script_file, quit=self.__quit_flag,
show_script=self.__show_script,
raise_relax_error=self.__raise_relax_error)
  File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 610, in run_script
    return console.interact(intro, local, script_file, quit,
show_script=show_script, raise_relax_error=raise_relax_error)
  File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 495, in 
interact_script
    exec_script(script_file, local)
  File &quot;/progs/relax-1.3.13/prompt/interpreter.py&quot;, line 383, in exec_script
    runpy.run_module(module, globals)
  File &quot;/usr/lib/python2.6/runpy.py&quot;, line 140, in run_module
    fname, loader, pkg_name)
  File &quot;/usr/lib/python2.6/runpy.py&quot;, line 34, in _run_code
    exec code in run_globals
  File &quot;/home1/hugh/data/pgm298bq/relax/dauvergne_protocol.py&quot;, line
216, in &lt;module&gt;
    dAuvergne_protocol(pipe_name=name, diff_model=DIFF_MODEL,
mf_models=MF_MODELS, local_tm_models=LOCAL_TM_MODELS,
grid_inc=GRID_INC, min_algor=MIN_ALGOR, mc_sim_num=MC_NUM,
conv_loop=CONV_LOOP)
  File &quot;/progs/relax-1.3.13/auto_analyses/dauvergne_protocol.py&quot;, line
223, in __init__
Traceback (most recent call last):
  File &quot;/progs/Linux/bin/relax13&quot;, line 7, in &lt;module&gt;
    relax.start()
  File &quot;/progs/relax-1.3.13/relax.py&quot;, line 100, in start
    processor.run()
  File &quot;/progs/relax-1.3.13/multi/uni_processor.py&quot;, line 139, in run
    self.callback.handle_exception(self, e)
  File &quot;/progs/relax-1.3.13/multi/processor.py&quot;, line 250, in
default_handle_exception
    traceback.print_exc(file=sys.stderr)
  File &quot;/usr/lib/python2.6/traceback.py&quot;, line 227, in print_exc
    print_exception(etype, value, tb, limit, file)
  File &quot;/usr/lib/python2.6/traceback.py&quot;, line 125, in print_exception
    print_tb(tb, limit, file)
  File &quot;/usr/lib/python2.6/traceback.py&quot;, line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File &quot;/usr/lib/python2.6/linecache.py&quot;, line 14, in getline
    lines = getlines(filename, module_globals)
  File &quot;/usr/lib/python2.6/linecache.py&quot;, line 40, in getlines
    return updatecache(filename, module_globals)
  File &quot;/usr/lib/python2.6/linecache.py&quot;, line 136, in updatecache
    lines = fp.readlines()
MemoryError
9078.655u 666.933s 10:55:29.66 24.7%    0+0k 241482000+0io 6665721pf+0w


</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00005" href="msg00005.html">Re: Problem during &quot;final&quot; run of d'Auvergne Protocol</a></strong>
<ul><li><em>From:</em> Edward d'Auvergne</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Mon Mar 05 09:40:05 2012</div>  
</body>
</html>
