<!-- MHonArc v2.6.16 -->
<!--X-Subject: Re: Exception raised during black&#45;box mf -->
<!--X-From-R13: "Sqjneq q'Ohiretar" <rqjneqNaze&#45;erynk.pbz> -->
<!--X-Date: Thu, 27 Sep 2012 16:28:12 +0200 -->
<!--X-Message-Id: CAED9pY&#45;YoCqOkU3wxEHmWrA==_6rjbH3OFTasDT8DpQB_Qxo0w@mail.gmail.com -->
<!--X-Content-Type: text/plain -->
<!--X-Reference: D1C66302&#45;B6CE&#45;4019&#45;8A97&#45;29A8CB6035CD@fmp&#45;berlin.de -->
<!--X-Reference: CAED9pY9qJr5b_iTZ1jfowAw4BSi9My7Pj6ORtaEqmxXtX02hcA@mail.gmail.com -->
<!--X-Reference: 5057B7160200000300025526@fmp&#45;berlin.de -->
<!--X-Reference: 675AA8A1&#45;44C9&#45;44B9&#45;9C49&#45;5B64ADF0A376@fmp&#45;berlin.de -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Re: Exception raised during black-box mf -- September 27, 2012 - 16:28</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Re: Exception raised during black-box mf</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00046" class="tabs">Index by Date</a> | <a href="threads.html#00046" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00045.html">Date Prev</a>] [Date Next] [<a href="msg00045.html">Thread Prev</a>] [<a href="msg00026.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: Martin Ballaschk &lt;ballaschk@xxxxxxxxxxxxx&gt;</li>
<li class="menuitem">
<em>Date</em>: Thu, 27 Sep 2012 16:27:42 +0200</li>
<li class="menuitem">
<em>Cc</em>: &quot;relax-users@xxxxxxx&quot; &lt;relax-users@xxxxxxx&gt;</li>
<li class="menuitem">
<em>Dkim-signature</em>: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=20120113;	h=mime-version:sender:in-reply-to:references:date	:x-google-sender-auth:message-id:subject:from:to:cc:content-type	:content-transfer-encoding;	bh=jreBxqknik8aJ383mG/4+URgJrlRN17yhxt26uWAmfE=;	b=x1JdK07T7/RiIufz5CER9CGaMVAUC+O1kM7Z6zA1hp+RGUFnq0HzcjJAbTIHK5eV2X	Qz/BK8PPswZm9fU82SWW0XsMVHeaIkjCwWnuBh0netNaodo2zlBa4SG9jlOuSOL76fn+	IPS9TWI03doIxD+8Vg+01aWu/iN4wWty2Wf11QJDSAsSYHCttc/g1BPPejIcyxRLwpOQ	Q+iGN3MO79rX1mK0Z7Zy2Uk//EudOxVwQLk2g34RTd+TbUAgoDVlo70M5/HizJefTfxq	5MAIv5ipXaurJLVt5X9cn8crrTzl5L317cS7XO8nvzcQqUPvyDd54lBcO7Iy8t48Sivk	FrJg==</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00046.html">CAED9pY-YoCqOkU3wxEHmWrA==_6rjbH3OFTasDT8DpQB_Qxo0w@mail.gmail.com</a>&gt;</li>
<li class="menuitem">
<em>References</em>: &lt;D1C66302-B6CE-4019-8A97-29A8CB6035CD@xxxxxxxxxxxxx&gt;	&lt;CAED9pY9qJr5b_iTZ1jfowAw4BSi9My7Pj6ORtaEqmxXtX02hcA@xxxxxxxxxxxxxx&gt;	&lt;5057B7160200000300025526@xxxxxxxxxxxxx&gt;	&lt;675AA8A1-44C9-44B9-9C49-5B64ADF0A376@xxxxxxxxxxxxx&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Edward d'Auvergne</strong> on September 27, 2012 - 16:28:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">Hi,

Thanks for the info!  I now won't bug you about creating bug reports
and will save myself some time not trying to debug the problem.

Cheers,

Edward


On 27 September 2012 16:17, Martin Ballaschk &lt;ballaschk@xxxxxxxxxxxxx&gt; wrote:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">Hi Edward, dear list readers,

turns out I made a mistake while importing the relaxation data. When I let 
relax read the correct data sets, everything works just fine.

Cheers,
Martin


On 17.09.2012, at 23:49, Martin Ballaschk &lt;ballaschk@xxxxxxxxxxxxx&gt; wrote:

</pre><blockquote class="blockquote"><pre style="margin: 0em;">Hi Edward,

a similar message pops up also when running relax in single-processor mode.

As soon as I'm back in Berlin I will try to make a minimal data set and 
post the required info with the bug report.

Thanks for your support

Cheers
Martin



Am 17.09.2012 um 11:10 schrieb &quot;Edward d'Auvergne&quot; &lt;edward@xxxxxxxxxxxxx&gt;:

</pre><blockquote class="blockquote"><pre style="margin: 0em;">Hi Martin,

Would you be able to create a bug report for this problem?  The link
for this is <a  rel="nofollow" href="https://gna.org/bugs/?func=additem&amp;group=relax">https://gna.org/bugs/?func=additem&amp;group=relax</a>.  The error
message you are seeing is complicated because you appear to be running
in Gary's mpi4py multi-processor mode.  Could you also try in the
uni-processor mode and see if the error exists there as well?  The
traceback error messages from this mode are much easier to interpret.

Useful information for the bug report would be the command you typed
at the command line, the error message in multi- and uni-processor
modes, and the output of:

$ relax --info

It might be also useful if you came up with a mini dataset of only a
few spin systems together with a script which trigger the bug and then
to attach these to the bug report.  You can slightly randomise the
data if you wish to keep the results confidential.

Cheers,

Edward





On 14 September 2012 09:28, Martin Ballaschk &lt;ballaschk@xxxxxxxxxxxxx&gt; 
wrote:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">Hi Edward,

I need a bit of help figuring out what was going wrong here. I started 
the fully-automated protocol via the GUI in relax 2.1.0 
(multi-processor).

First, relax successfully fitted the local_tm:

</pre><blockquote class="blockquote"><pre style="margin: 0em;">relax&gt; results.write(file='results', 
dir='/home/tron/relax-martin/b2m/local_tm/aic', compress_type=1, 
force=True)
Opening the file '/home/tron/relax-martin/b2m/local_tm/aic/results.bz2' 
for writing.
</pre></blockquote><pre style="margin: 0em;">



Then, it started with the spherical diffusion tensor and raised the 
following error message.

</pre><blockquote class="blockquote"><pre style="margin: 0em;">relax&gt; pipe.create(pipe_name='sphere - mf (Thu Sep 13 15:47:14 2012)', 
pipe_type='mf', bundle='mf (Thu Sep 13 15:47:14 2012)')

relax&gt; results.read(file='results', 
dir='/home/tron/relax-martin/b2m/local_tm/aic')
Opening the file '/home/tron/relax-martin/b2m/local_tm/aic/results.bz2' 
for reading.

relax&gt; model_free.remove_tm(spin_id=None)

relax&gt; diffusion_tensor.init(params=1e-08, time_scale=1.0, d_scale=1.0, 
angle_units='deg', param_types=0, spheroid_type=None, fixed=False)

relax&gt; fix(element='all_spins', fixed=True)

relax&gt; grid_search(lower=None, upper=None, inc=11, constraints=True, 
verbosity=1)


Over-fit spin deselection.

Only diffusion tensor parameters will be used.
Parallelised diffusion tensor grid search.
Exception raised in thread.

Traceback (most recent call last):
File &quot;/opt/relax-2.1.0/gui/analyses/execute.py&quot;, line 87, in run
  self.run_analysis()
File &quot;/opt/relax-2.1.0/gui/analyses/auto_model_free.py&quot;, line 803, in 
run_analysis
  dauvergne_protocol.dAuvergne_protocol(pipe_name=self.data.pipe_name, 
pipe_bundle=self.data.pipe_bundle, results_dir=self.data.save_dir, 
diff_model=self.data.global_models, mf_models=self.data.mf_models, 
local_tm_models=self.data.local_tm_models, grid_inc=self.data.inc, 
diff_tensor_grid_inc=self.data.diff_tensor_grid_inc, 
mc_sim_num=self.data.mc_sim_num, max_iter=self.data.max_iter, 
conv_loop=self.data.conv_loop)
File &quot;/opt/relax-2.1.0/auto_analyses/dauvergne_protocol.py&quot;, line 235, 
in __init__
  self.execute()
File &quot;/opt/relax-2.1.0/auto_analyses/dauvergne_protocol.py&quot;, line 619, 
in execute
  self.interpreter.grid_search(inc=inc)
File &quot;/opt/relax-2.1.0/prompt/uf_objects.py&quot;, line 219, in __call__
  self._backend(*new_args, **uf_kargs)
File &quot;/opt/relax-2.1.0/generic_fns/minimise.py&quot;, line 140, in 
grid_search
  grid_search(lower=lower, upper=upper, inc=inc, 
constraints=constraints, verbosity=verbosity)
File &quot;/opt/relax-2.1.0/specific_fns/model_free/mf_minimise.py&quot;, line 
1493, in grid_search
  self.minimise(min_algor='grid', lower=lower, upper=upper, inc=inc, 
constraints=constraints, verbosity=verbosity, sim_index=sim_index)
File &quot;/opt/relax-2.1.0/specific_fns/model_free/mf_minimise.py&quot;, line 
1817, in minimise
  processor.run_queue()
File &quot;/opt/relax-2.1.0/multi/processor.py&quot;, line 621, in run_queue
  self.run_command_queue(lqueue)
File &quot;/opt/relax-2.1.0/multi/processor.py&quot;, line 605, in 
run_command_queue
  result_queue.put(result)
File &quot;/opt/relax-2.1.0/multi/result_queue.py&quot;, line 90, in put
  super(Threaded_result_queue, self).put(job)
File &quot;/opt/relax-2.1.0/multi/result_queue.py&quot;, line 52, in put
  self.processor.process_result(job)
File &quot;/opt/relax-2.1.0/multi/multi_processor_base.py&quot;, line 123, in 
process_result
  result.run(self, memo)
File &quot;/opt/relax-2.1.0/multi/result_commands.py&quot;, line 141, in run
  raise self.exception
Capturing_exception:

------------------------------------------------------------------------------------------------------------------------

File &quot;/opt/relax-2.1.0/multi/processor.py&quot;, line 521, in run
  command.run(self, completed)
File 
&quot;/opt/relax-2.1.0/specific_fns/model_free/multi_processor_commands.py&quot;, 
line 129, in run
  results = self.optimise()
File 
&quot;/opt/relax-2.1.0/specific_fns/model_free/multi_processor_commands.py&quot;, 
line 175, in optimise
  results = grid_point_array(func=self.mf.func, args=(), 
points=self.opt_params.subdivision, verbosity=self.opt_params.verbosity)
File &quot;/opt/relax-2.1.0/minfx/grid.py&quot;, line 256, in grid_point_array
  n = len(points[0])


Nested Exception from sub processor
Rank: 1 Name: hyperion-pid7244
Exception type: IndexError
Message: index out of bounds

------------------------------------------------------------------------------------------------------------------------
</pre></blockquote><pre style="margin: 0em;">



I'm not very good in reading these kinds of traceback error messages, 
and in this case it's hard for me to see why the grid search failed.

I noticed that my data are partly faulty: there is a single amino acid 
with a HetNOE &gt; 1. This is a artifact I have to look into yet, I suppose 
it is a S/N problem of the original spectra (very weak peak?). Could 
that be the reason for the exception?

I'd be grateful if you could provide a bit of support (again).

Cheers
Martin






_______________________________________________
relax (<a  rel="nofollow" href="http://www.nmr-relax.com">http://www.nmr-relax.com</a>)

This is the relax-users mailing list
relax-users@xxxxxxx

To unsubscribe from this list, get a password
reminder, or change your subscription options,
visit the list information page at
<a  rel="nofollow" href="https://mail.gna.org/listinfo/relax-users">https://mail.gna.org/listinfo/relax-users</a>
</pre></blockquote></blockquote></blockquote><pre style="margin: 0em;">


_______________________________________________
relax (<a  rel="nofollow" href="http://www.nmr-relax.com">http://www.nmr-relax.com</a>)

This is the relax-users mailing list
relax-users@xxxxxxx

To unsubscribe from this list, get a password
reminder, or change your subscription options,
visit the list information page at
<a  rel="nofollow" href="https://mail.gna.org/listinfo/relax-users">https://mail.gna.org/listinfo/relax-users</a>
</pre></blockquote><pre style="margin: 0em;">


</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<!--X-Follow-Ups-End-->
<!--X-References-->
<ul><li><strong>References</strong>:
<ul>
<li><strong><a name="00024" href="msg00024.html">Exception raised during black-box mf</a></strong>
<ul><li><em>From:</em> Martin Ballaschk</li></ul></li>
<li><strong><a name="00025" href="msg00025.html">Re: Exception raised during black-box mf</a></strong>
<ul><li><em>From:</em> Edward d'Auvergne</li></ul></li>
<li><strong><a name="00045" href="msg00045.html">Re: Exception raised during black-box mf</a></strong>
<ul><li><em>From:</em> Martin Ballaschk</li></ul></li>
</ul></li></ul>
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Thu Sep 27 16:40:16 2012</div>  
</body>
</html>
