<!-- MHonArc v2.6.18 -->
<!--X-Subject: Error message upon PDB loading -->
<!--X-From-R13: Egrsnab Zhpvnab Qvheyv &#60;fgrsnab.pvheyvNhavob.vg> -->
<!--X-Date: Tue, 18 Mar 2014 10:13:19 +0100 -->
<!--X-Message-Id: 1C7F8F29&#45;B947&#45;4EDF&#45;8046&#45;F22930ED3C3F@unibo.it -->
<!--X-Content-Type: text/plain -->
<!--X-Reference: B26484E7&#45;DEA1&#45;40E7&#45;B4CB&#45;06F92E64BD2D@unibo.it -->
<!--X-Reference: CAED9pY_oqMEsdXhdEsXmZH7Wf&#45;9Vj_e8KsuODOxO9drtJWfXpA@mail.gmail.com -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Error message upon PDB loading -- March 18, 2014 - 10:13</title>
<link rel="stylesheet" type="text/css" href="/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="https://gna.org/images/gna.theme/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Error message upon PDB loading</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00030" class="tabs">Index by Date</a> | <a href="threads.html#00030" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00029.html">Date Prev</a>] [<a href="msg00031.html">Date Next</a>] [<a href="msg00036.html">Thread Prev</a>] [<a href="msg00031.html">Thread Next</a>]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: Edward d'Auvergne &lt;edward@xxxxxxxxxxxxx&gt;</li>
<li class="menuitem">
<em>Date</em>: Tue, 18 Mar 2014 09:13:08 +0000</li>
<li class="menuitem">
<em>Accept-language</em>: it-IT, en-US</li>
<li class="menuitem">
<em>Cc</em>: &quot;relax-users@xxxxxxx&quot; &lt;relax-users@xxxxxxx&gt;</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00030.html">1C7F8F29-B947-4EDF-8046-F22930ED3C3F@unibo.it</a>&gt;</li>
<li class="menuitem">
<em>References</em>: &lt;<a href="msg00015.html">B26484E7-DEA1-40E7-B4CB-06F92E64BD2D@unibo.it</a>&gt; &lt;<a href="msg00025.html">CAED9pY_oqMEsdXhdEsXmZH7Wf-9Vj_e8KsuODOxO9drtJWfXpA@mail.gmail.com</a>&gt;</li>
<li class="menuitem">
<em>Thread-index</em>: AQHPQopHVuHLmg2e0U65nSNTkyaBfQ==</li>
<li class="menuitem">
<em>Thread-topic</em>: Error message upon PDB loading</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Stefano Luciano Ciurli</strong> on March 18, 2014 - 10:13:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">Hello,
I hope I do not bug you too often, but I keep receiving error messages. Here 
is one, upon loading a PDB file generated using Chimera, and no spins are 
loaded in the spin viewer. I am using 3.1.7.
Stefano

Internal relax PDB parser.
Opening the file '/Users/stefano/Desktop/13-BpUreE-NMR/Manuscript/Figure 6,7 
- Dynamics/relax/dimer_H.pdb' for reading.
Traceback (most recent call last):
  File &quot;gui/interpreter.pyc&quot;, line 303, in run
  File &quot;pipe_control/structure/main.pyc&quot;, line 722, in read_pdb
  File &quot;lib/structure/internal/object.pyc&quot;, line 1813, in load_pdb
  File &quot;lib/structure/internal/object.pyc&quot;, line 500, in _parse_pdb_ss
  File &quot;lib/structure/pdb_read.pyc&quot;, line 1221, in sheet
IndexError: string index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File &quot;threading.pyc&quot;, line 808, in __bootstrap_inner
  File &quot;gui/interpreter.pyc&quot;, line 323, in run
  File &quot;status.pyc&quot;, line 369, in release
  File &quot;status.pyc&quot;, line 413, in notify
  File &quot;gui/analyses/auto_model_free.pyc&quot;, line 276, in activate
  File 
&quot;/Applications/relax.app/Contents/Resources/lib/python2.7/wx/_core.py&quot;, line 
16769, in CallAfter
AssertionError: callableObj is not callable

</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<ul><li><strong>Follow-Ups</strong>:
<ul>
<li><strong><a name="00032" href="msg00032.html">Re: Error message upon PDB loading</a></strong>
<ul><li><em>From:</em> Troels Emtek√¶r Linnet</li></ul></li>
<li><strong><a name="00031" href="msg00031.html">Re: Error message upon PDB loading</a></strong>
<ul><li><em>From:</em> Edward d'Auvergne</li></ul></li>
</ul></li></ul>
<!--X-Follow-Ups-End-->
<!--X-References-->
<ul><li><strong>References</strong>:
<ul>
<li><strong><a name="00015" href="msg00015.html">error message</a></strong>
<ul><li><em>From:</em> Stefano Luciano Ciurli</li></ul></li>
<li><strong><a name="00025" href="msg00025.html">Re: error message</a></strong>
<ul><li><em>From:</em> Edward d'Auvergne</li></ul></li>
</ul></li></ul>
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer">You are on the <a href="http://gna.org">Gna!</a> mail server.</div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Tue Mar 18 17:40:13 2014</div>  
</body>
</html>
