<!-- MHonArc v2.6.16 -->
<!--X-Subject: Re: Error when running full_analysis.py script -->
<!--X-From-R13: "Sqjneq q'Ohiretar" <rqjneqNaze&#45;erynk.pbz> -->
<!--X-Date: Wed, 28 Oct 2009 17:09:56 +0100 -->
<!--X-Message-Id: 7f080ed10910280909h1220982bs66c89ac0172694e0@mail.gmail.com -->
<!--X-Content-Type: text/plain -->
<!--X-Reference: 20091005161313.f3715bbf@mail.ccrc.uga.edu -->
<!--X-Reference: 7f080ed10910060031l7b095e79q9d804bdebbe23204@mail.gmail.com -->
<!--X-Reference: 12A9D1A2CF9D4536985EA794893504B7@Mercurio -->
<!--X-Reference: D4A2FB2CF9A04EF28BC6DB4A3EC37A47@Mercurio -->
<!--X-Reference: 4ADF56D6.6080306@ulaval.ca -->
<!--X-Reference: E45CDDF4A4E54B34A36BFBA62E6BFF20@Mercurio -->
<!--X-Reference: 7f080ed10910270301r6ca3c685t4a968772140996dd@mail.gmail.com -->
<!--X-Reference: 15191092434C4019967C0DB927625E5F@Mercurio -->
<!--X-Reference: 7f080ed10910280550n63c235cdxe170a471843de554@mail.gmail.com -->
<!--X-Reference: 3426FD7656C2435291DF445C5453087E@Mercurio -->
<!--X-Head-End-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Re: Error when running full_analysis.py script -- October 28, 2009 - 17:09</title>
<link rel="stylesheet" type="text/css" href="/mail.gna.org/archives-color-gna.css"> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<h2><img src="/mail.gna.org/images/mail.orig.png" width="48" height="48"
alt="mail" class="pageicon" />Re: Error when running full_analysis.py script</h2>
<br />
<div class="topmenu">
<a href="../" class="tabs">Others Months</a> | <a href="index.html#00020" class="tabs">Index by Date</a> | <a href="threads.html#00020" class="tabs">Thread Index</a><br />
<span class="smaller">&gt;&gt;&nbsp;&nbsp;
[<a href="msg00019.html">Date Prev</a>] [Date Next] [<a href="msg00019.html">Thread Prev</a>] [Thread Next]
</div>

<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<h3><a name="header" href="#header">Header</a></h3>
<!--X-Subject-Header-End-->
<!--X-Head-of-Message-->
<ul class="headdata">
<li class="menuitem">
<em>To</em>: Tiago Pais &lt;tpais@xxxxxxxxxxx&gt;</li>
<li class="menuitem">
<em>Date</em>: Wed, 28 Oct 2009 17:09:17 +0100</li>
<li class="menuitem">
<em>Cc</em>: relax-users@xxxxxxx</li>
<li class="menuitem">
<em>Message-id</em>: &lt;<a href="msg00020.html">7f080ed10910280909h1220982bs66c89ac0172694e0@mail.gmail.com</a>&gt;</li>
<li class="menuitem">
<em>References</em>: &lt;20091005161313.f3715bbf@xxxxxxxxxxxxxxxxx&gt;	&lt;7f080ed10910060031l7b095e79q9d804bdebbe23204@xxxxxxxxxxxxxx&gt;	&lt;<a href="msg00006.html">12A9D1A2CF9D4536985EA794893504B7@Mercurio</a>&gt;	&lt;<a href="msg00007.html">D4A2FB2CF9A04EF28BC6DB4A3EC37A47@Mercurio</a>&gt;	&lt;4ADF56D6.6080306@xxxxxxxxx&gt;	&lt;<a href="msg00009.html">E45CDDF4A4E54B34A36BFBA62E6BFF20@Mercurio</a>&gt;	&lt;7f080ed10910270301r6ca3c685t4a968772140996dd@xxxxxxxxxxxxxx&gt;	&lt;<a href="msg00015.html">15191092434C4019967C0DB927625E5F@Mercurio</a>&gt;	&lt;7f080ed10910280550n63c235cdxe170a471843de554@xxxxxxxxxxxxxx&gt;	&lt;<a href="msg00019.html">3426FD7656C2435291DF445C5453087E@Mercurio</a>&gt;</li>
</ul>
<!--X-Head-of-Message-End-->
<!--X-Head-Body-Sep-Begin-->
</div><!-- end headdata -->
<br />
<h3><a name="content" href="#content">Content</a></h3>
<div class="postedby">Posted by <strong>Edward d'Auvergne</strong> on October 28, 2009 - 17:09:</div>
<div class="msgdata">
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<pre style="margin: 0em;">Hi,

It may be due to single field strength data, but I would guess that it
is some other problem.  If it reappears when you are analysing your
data in another way, then I'll instantly fix it.  This will require a
bug report with truncated data so that I can replicate the bug, then
it usually takes me ~5 min to fix, otherwise it will take much longer
for me to find the site of the problem.  I have talked in detail about
the issue of single field strength data before.  Rather than repeating
everything again, I would recommend you to read my post at
<a  rel="nofollow" href="/mail.gna.org/public/relax-users/2008-03/msg00004.html">https://mail.gna.org/public/relax-users/2008-03/msg00004.html</a>.  The
first 2 paragraphs are all that are relevant.  I hope this helps.

Regards,

Edward



2009/10/28 Tiago Pais &lt;tpais@xxxxxxxxxxx&gt;:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">I find no evidence of a problem related to data not loaded.
On the other hand I didn't notice the information at the beginning of the
script stating that &quot;multiple magnetic field strength&quot; data was essential.
Do you think this might be really the problem?
How can I solve it? I have data acquired only at one field strength. Is
there another sample script more suitable?
Best regards
TiagoP

-----Original Message-----
From: edward.dauvergne@xxxxxxxxx [<a  rel="nofollow" href="mailto:edward.dauvergne@xxxxxxxxx">mailto:edward.dauvergne@xxxxxxxxx</a>] On
Behalf Of Edward d'Auvergne
Sent: quarta-feira, 28 de Outubro de 2009 12:50
To: Tiago Pais
Cc: relax-users@xxxxxxx
Subject: Re: Error when running full_analysis.py script

Hi,

I'm not exactly sure what the problem is, but I would get that there
is a warning thrown when loading the relaxation data that no data was
loaded?  This error has been encountered before, but I thought it had
been fixed.  Another issue is that your are using single field
strength data, but in the introduction for this script it says:

&quot;Importantly data at multiple magnetic field strengths is essential
for this analysis.&quot;

I've now added a check for this to the script (available from the
download link at
<a  rel="nofollow" href="http://svn.gna.org/viewcvs/relax/1.3/sample_scripts/full_analysis.py?rev=983">http://svn.gna.org/viewcvs/relax/1.3/sample_scripts/full_analysis.py?rev=983</a>
4&amp;view=markup).

Cheers,

Edward



2009/10/27 Tiago Pais &lt;tpais@xxxxxxxxxxx&gt;:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">Sorry, forgot to attach the script.
TP

-----Original Message-----
From: Tiago Pais [<a  rel="nofollow" href="mailto:tpais@xxxxxxxxxxx">mailto:tpais@xxxxxxxxxxx</a>]
Sent: terça-feira, 27 de Outubro de 2009 12:17
To: 'Edward d'Auvergne'
Cc: 'Sébastien Morin'; 'Boaz Shapira'; 'relax-users@xxxxxxx'
Subject: RE: Error when running full_analysis.py script

Dear Edward,
I will try to provid the most complete information since I have not
</pre></blockquote><pre style="margin: 0em;">managed
</pre><blockquote class="blockquote"><pre style="margin: 0em;">to solve the problem yet:

1- Relax version 1.3.4 running under Ubuntu 9.04 virtual machine
2- I have executed the script in the command line by typing &quot;relax
full_analysis.py&quot;. The location is /home/tpais/ModelFree/PHS/teste/
3- I am in the initial steps of the script with the diffusion model set to
&quot;local_tm&quot;.
4-the script still manages to run for a couple of minutes executing some
Newton minimizations and still writes 4 files (tm0, tm1,...) within the
subdirectory &quot;/local_tm&quot;. These are the last lines showing up before the
error occurs:
&quot;File &quot;full_analysis.py&quot;, line 220, in __init__
   self.multi_model(local_tm=True)
 File &quot;full_analysis.py&quot;, line 662, in multi_model
   grid_search(inc=GRID_INC)
 File &quot;/usr/local/relax/prompt/minimisation.py&quot;, line 156, in grid_search
   minimise.grid_search(lower=lower, upper=upper, inc=inc,
constraints=constraints, verbosity=verbosity)
 File &quot;/usr/local/relax/generic_fns/minimise.py&quot;, line 191, in grid_search
   grid_search(lower=lower, upper=upper, inc=inc, constraints=constraints,
verbosity=verbosity)
 File &quot;/usr/local/relax/specific_fns/model_free/mf_minimise.py&quot;, line 479,
in grid_search
   self.minimise(min_algor='grid', lower=lower, upper=upper, inc=inc,
constraints=constraints, verbosity=verbosity, sim_index=sim_index)
 File &quot;/usr/local/relax/specific_fns/model_free/mf_minimise.py&quot;, line 789,
in minimise
   model_type = self.determine_model_type()
 File &quot;/usr/local/relax/specific_fns/model_free/main.py&quot;, line 1015, in
determine_model_type
   if cdp.diff_tensor.fixed:
AttributeError: 'PipeContainer' object has no attribute 'diff_tensor'&quot;


5- I also send attached the script as I am using it.

By the way, I tried to run the script with the new function and it gave an
indentation error (&quot;IndentationError: expected an indented block&quot;)
</pre></blockquote><pre style="margin: 0em;">probably
</pre><blockquote class="blockquote"><pre style="margin: 0em;">because I copy/past it directly from the link you provided)

Regards,
TiagoP



-----Original Message-----
From: edward.dauvergne@xxxxxxxxx [<a  rel="nofollow" href="mailto:edward.dauvergne@xxxxxxxxx">mailto:edward.dauvergne@xxxxxxxxx</a>] On
Behalf Of Edward d'Auvergne
Sent: terça-feira, 27 de Outubro de 2009 10:02
To: Tiago Pais
Cc: Sébastien Morin; Boaz Shapira; relax-users@xxxxxxx
Subject: Re: Error when running full_analysis.py script

Dear Tiago,

This is a hard one to catch.  I have just added a function to this
script to check the validity of the user variables

</pre></blockquote><pre style="margin: 0em;">(<a  rel="nofollow" href="http://svn.gna.org/viewcvs/relax/1.3/sample_scripts/full_analysis.py?rev=97">http://svn.gna.org/viewcvs/relax/1.3/sample_scripts/full_analysis.py?rev=97</a>
</pre><blockquote class="blockquote"><pre style="margin: 0em;">94&amp;view=markup).
 This should give better error messages specifically identifying the
problem.  For this second issue you are having, it is a little hard to
see what the problem is.  Would you be able to supply a little more
information.  For example the version of relax you are using, the full
error message, how you have executed the full_analysis.py script and
at what stage you are up to, etc.  With more information, I should be
able to track down the issue.

Cheers,

Edward



2009/10/22 Tiago Pais &lt;tpais@xxxxxxxxxxx&gt;:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">Hi Sebastien,
The thing is it was not exactly an error of the script. In the line 639
</pre></blockquote><pre style="margin: 0em;">you
</pre><blockquote class="blockquote"><pre style="margin: 0em;">have to adjust the script so that it agrees with the format of the
</pre></blockquote><pre style="margin: 0em;">function
</pre><blockquote class="blockquote"><pre style="margin: 0em;">that you have used in line 174 &quot;Relax_Data=[...&quot;. If in line 174 you
describe the data sets with only three parameters (e.g.[Rilabel, freq,
file]) then, in line 639 you have to adapt the function so that the
</pre></blockquote><pre style="margin: 0em;">program
</pre><blockquote class="blockquote"><pre style="margin: 0em;">reads only three sets of parameters (e.g. relax_data.read(data[0],
</pre></blockquote><pre style="margin: 0em;">data[1],
</pre><blockquote class="blockquote"><pre style="margin: 0em;">data[2], data[3]) while in the original file was set to read 13.
This is beginners' stuff, but that's exactly what I am with respect to
</pre></blockquote><pre style="margin: 0em;">RELAX
</pre><blockquote class="blockquote"><pre style="margin: 0em;">and PYTHON, so it may be usefull for other beginners.

However, I still have not managed to run the script to the end. At the
moment I am stuck with yet another error message: AttributeError:
'PipeContainer' object has no attribute 'diff_tensor'

If anyone can help me and avoid that I loose time with this probably easy
</pre></blockquote><pre style="margin: 0em;">to
</pre><blockquote class="blockquote"><pre style="margin: 0em;">solve error, please do.
Thanks
Tiago P

-----Original Message-----
From: Sébastien Morin [<a  rel="nofollow" href="mailto:sebastien.morin.1@xxxxxxxxx">mailto:sebastien.morin.1@xxxxxxxxx</a>]
Sent: quarta-feira, 21 de Outubro de 2009 19:46
To: Tiago Pais
Cc: 'Edward d'Auvergne'; 'Boaz Shapira'; relax-users@xxxxxxx
Subject: Re: Error when running full_analysis.py script

Dear Tiago,

Just for the logs, could you tell us what was the problem ?

Regards,


Sébastien


Tiago Pais wrote:
</pre><blockquote class="blockquote"><pre style="margin: 0em;">Ok, managed to solve this already.
Cheers
Tiago

-----Original Message-----
From: relax-users-bounces@xxxxxxx [<a  rel="nofollow" href="mailto:relax-users-bounces@xxxxxxx">mailto:relax-users-bounces@xxxxxxx</a>]
</pre></blockquote></blockquote></blockquote><pre style="margin: 0em;">On
</pre><blockquote class="blockquote"><blockquote class="blockquote"><blockquote class="blockquote"><pre style="margin: 0em;">Behalf Of Tiago Pais
Sent: quarta-feira, 21 de Outubro de 2009 15:53
To: 'Edward d'Auvergne'; 'Boaz Shapira'
Cc: relax-users@xxxxxxx
Subject: Error when running full_analysis.py script

Dear all,
I am using 15N relaxation data previously analyzed to test some of the
scripts available in Relax to make sure that I am using it correctly.
However, I get the following error message when running the sample
</pre></blockquote></blockquote></blockquote><pre style="margin: 0em;">script
</pre><blockquote class="blockquote"><blockquote class="blockquote"><blockquote class="blockquote"><pre style="margin: 0em;">full_analysis.py: &quot;List Index out of Range&quot;
Below is &quot;print screen&quot; where the error shows up at the bottom:

&quot;None       149        Q          None       None

relax&gt; spin.name(spin_id=None, name='N', force=False)
Traceback (most recent call last):
  File &quot;/usr/local/bin/relax&quot;, line 418, in &lt;module&gt;
    Relax()
  File &quot;/usr/local/bin/relax&quot;, line 127, in __init__
    self.interpreter.run(self.script_file)
  File &quot;/usr/local/relax/prompt/interpreter.py&quot;, line 276, in run
    return run_script(intro=self.__intro_string, local=self.local,
script_file=script_file, quit=self.__quit_flag,
show_script=self.__show_script,
raise_relax_error=self.__raise_relax_error)
  File &quot;/usr/local/relax/prompt/interpreter.py&quot;, line 537, in run_script
    return console.interact(intro, local, script_file, quit,
show_script=show_script, raise_relax_error=raise_relax_error)
  File &quot;/usr/local/relax/prompt/interpreter.py&quot;, line 433, in
interact_script
    execfile(script_file, local)
  File &quot;full_analysis.py&quot;, line 671, in &lt;module&gt;
    Main(self.relax)
  File &quot;full_analysis.py&quot;, line 220, in __init__
    self.multi_model(local_tm=True)
  File &quot;full_analysis.py&quot;, line 639, in multi_model
    relax_data.read(data[0], data[1], data[2], data[3], data[4],
</pre></blockquote></blockquote></blockquote><pre style="margin: 0em;">data[5],
</pre><blockquote class="blockquote"><blockquote class="blockquote"><blockquote class="blockquote"><pre style="margin: 0em;">data[6], data[7], data[8], data[9], data[10], data[11],
data[12])
IndexError: list index out of range&quot;

I can't understand if the error relates to the last command listed,
</pre></blockquote><pre style="margin: 0em;">actually
</pre><blockquote class="blockquote"><pre style="margin: 0em;">I can't understand the command given in this line (639) - what is it
</pre></blockquote><pre style="margin: 0em;">suppose
</pre><blockquote class="blockquote"><pre style="margin: 0em;">to do?

Best regards
TiagoP


_______________________________________________
relax (<a  rel="nofollow" href="http://nmr-relax.com">http://nmr-relax.com</a>)

This is the relax-users mailing list
relax-users@xxxxxxx

To unsubscribe from this list, get a password
reminder, or change your subscription options,
visit the list information page at
<a  rel="nofollow" href="/mail.gna.org/listinfo/relax-users">https://mail.gna.org/listinfo/relax-users</a>


_______________________________________________
relax (<a  rel="nofollow" href="http://nmr-relax.com">http://nmr-relax.com</a>)

This is the relax-users mailing list
relax-users@xxxxxxx

To unsubscribe from this list, get a password
reminder, or change your subscription options,
visit the list information page at
<a  rel="nofollow" href="/mail.gna.org/listinfo/relax-users">https://mail.gna.org/listinfo/relax-users</a>

</pre></blockquote><pre style="margin: 0em;">


--
Sébastien Morin
PhD Student
S. Gagné NMR Laboratory
Université Laval &amp; PROTEO
Québec, Canada


</pre></blockquote><pre style="margin: 0em;">

_______________________________________________
relax (<a  rel="nofollow" href="http://nmr-relax.com">http://nmr-relax.com</a>)

This is the relax-users mailing list
relax-users@xxxxxxx

To unsubscribe from this list, get a password
reminder, or change your subscription options,
visit the list information page at
<a  rel="nofollow" href="/mail.gna.org/listinfo/relax-users">https://mail.gna.org/listinfo/relax-users</a>


</pre></blockquote><pre style="margin: 0em;">


</pre></blockquote><pre style="margin: 0em;">


</pre>
<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
</div><!-- end msgdata -->
<br />
<h3><a name="related" href="#related">Related Messages</a></h3>
<div class="relateddata">
<!--X-Follow-Ups-End-->
<!--X-References-->
<ul><li><strong>References</strong>:
<ul>
<li><strong><a name="00004" href="msg00004.html">Re: SRLS</a></strong>
<ul><li><em>From:</em> Edward d'Auvergne</li></ul></li>
<li><strong><a name="00006" href="msg00006.html">Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Tiago Pais</li></ul></li>
<li><strong><a name="00007" href="msg00007.html">RE: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Tiago Pais</li></ul></li>
<li><strong><a name="00008" href="msg00008.html">Re: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Sébastien Morin</li></ul></li>
<li><strong><a name="00009" href="msg00009.html">RE: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Tiago Pais</li></ul></li>
<li><strong><a name="00012" href="msg00012.html">Re: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Edward d'Auvergne</li></ul></li>
<li><strong><a name="00015" href="msg00015.html">RE: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Tiago Pais</li></ul></li>
<li><strong><a name="00018" href="msg00018.html">Re: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Edward d'Auvergne</li></ul></li>
<li><strong><a name="00019" href="msg00019.html">RE: Error when running full_analysis.py script</a></strong>
<ul><li><em>From:</em> Tiago Pais</li></ul></li>
</ul></li></ul>
<!--X-References-End-->
<!--X-BotPNI-->
</div><!-- end relateddata -->
<!-- NoBotLinksApartFromRelatedMessages -->

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
<div class="footer"></div><br />
<div class="right">Powered by <a href="http://www.mhonarc.org">MHonArc</a>, Updated Wed Oct 28 17:20:17 2009</div>  
</body>
</html>
